//
//  UserTodoListViewController.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/2/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import KRProgressHUD

class UserTodoListViewController: UIViewController
{
    
    @IBOutlet weak var userTodoTableView: UITableView!
    
    var presenter: UserTodoListPresenterProtocol?
    var userId: Int?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    private func setup(){
        guard let userId = userId else{ return }
        presenter = UserTodoListPresenter(userId: userId, view: self)
        presenter?.getTodoList()
    }
    
}

extension UserTodoListViewController: UserTodoListViewProtocol{
    func showTodoList() {
        userTodoTableView.reloadData()
    }
    
    func showLoading() {
        KRProgressHUD.show()
    }
    
    func hideLoading() {
        KRProgressHUD.dismiss()
    }
    
    func showError(with message: String) {
        KRProgressHUD.showError(withMessage: message)
    }
    
}

extension UserTodoListViewController: UITableViewDelegate,UITableViewDataSource{
   
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter?.todoViewModels.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cellViewModel = presenter?.todoViewModels[indexPath.row] else{ return UITableViewCell() }
        let cell = tableView.dequeueReusableCell(withIdentifier: UserTodoTableViewCell.IDENTIFIER, for: indexPath) as! UserTodoTableViewCell
        cell.config(with: cellViewModel)
        return cell
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        cell.alpha = 0
        UIView.animate(
            withDuration: 0.5,
            delay: 0.05 * Double(indexPath.row),
            animations: {
                cell.alpha = 1
        })
    }
}

